### ISSUE TITLE
API: Table API

### ISSUE THREAD

**Issue by davidsneighbour** [getbooka/booka-issues#188]
# Tasks

- [ ] create generic table REST API functions that return values page-able/searchable
- [ ] add system to define access to these tables
  - [ ] class property $access with min-role to access this table
  - [ ] overwritable with custom threshold table-$TABLENAME$-access
- [ ] use [bootstrap-vue table container](https://bootstrap-vue.org/docs/components/table) and generic fill script for all occurences
- [ ] make columns configurable via localStorage (or maybe user settings?)
- [ ] set default column set via class property
- [ ] set available columns via class property

# API format for table object

- status - http status to check against on ajax tables
- config
  - columns - column setup
  - params - handing through the table setup
- data - associative array with the field contents
- error - error data
