### ISSUE TITLE
RFC: Payment Gateway Integration (Paypal) for public bookings

### ISSUE THREAD

**Issue by davidsneighbour** [getbooka/booka-issues#222]
_work in progress, will probably change_

Integration of [Omnipay](https://github.com/thephpleague/omnipay) for online payment gateways. Initially we create this integration using Paypal Express, goal is to easily extend the available services and to make this available too for agency invoices in a later step.

### Workflow

1. customer fills form
2. customer sends form
3. booking is created, status "pending"
4. customer sees booking details page with status and payment options
5. customer pays via gateway
6. payment is registered and status changed according to amount and setup

### Todo

- [ ] creation of a details page for each booking
- [ ] show payment options and open amount on that page
- [ ] link to payment gateway (Paypal) with amount, comment and webhook for response
- [ ] on response link react to whatever the gateway is responding and set booking to paid/issue
- [ ] add payments to accounting
- [ ] add flexible settings system for gateways

### Settings

- [ ] payment cascade
  - [ ] percentage required to set booking to "reserved"
  - [ ] percentage required to set booking to "booked"
  - [ ] if only one step is used then "booked" needs to be used
  - [ ] set up dates/thresholds for availability of payment options
  - [ ] add text for readable payment options
- [ ] setup payment gateway (Paypal)
  - [ ] enable/disable
  - [ ] apikeys/hooks

### Email Templates

- [ ] create automatic email templates
  - [ ] can't be empty
  - [ ] can't be deleted
  - [ ] have unique system-id
  - [ ] must have certain variables in them on save
- [ ] Booking Created
- [ ] Payment Received
- [ ] Payment Issue
- [ ] Payment Required (when the date to pay is near)
- [ ] Booking Status Change

### Project

see https://github.com/davidsneighbour/booka-issues/projects/10
