### ISSUE TITLE
Add payments with custom date

### ISSUE THREAD

**Issue by davidsneighbour** [getbooka/booka-issues#224]
Add the option to change the date for payments (as opposed to being saved at the exact time the payment is saved.

### ToDo

- [ ] enable with threshold field
- [ ] check what the implications to cashbooks/accounts and validity are
- [ ] printing a report (like cashbook report for date X) should lock dates up to the end of the report so nothing can be changed post
